### ISSUE TITLE
Crowdsale rate should not be updatable

### ISSUE THREAD

**Issue by tommyz7** [Onessus/void-token#25]
https://github.com/Onessus/void-token/blob/8b25e3d790c7fdb2b78da71c56b423d89e141821/contracts/Crowdsale.sol#L105

You may want to discuss with Dante if this function is the way to go. Users may argue that you can change your rate any time to make token super expensive or super cheap. Now that we have our rate fixed to Ethereum this probably should be hardcoded in the contract.

**Comment by 3th3r3um** [comment]
Good call, I meant to remove that setter but I never got around to it. It's definitely detrimental now that we're not actively tethering to USD. I'll remove it.
