### ISSUE TITLE
change isPurchaseEnabled to whenNotPaused/whenPaused modifiers

### ISSUE THREAD

**Issue by tommyz7** [Onessus/void-token#26]
https://github.com/Onessus/void-token/blob/8b25e3d790c7fdb2b78da71c56b423d89e141821/contracts/Crowdsale.sol#L88

I'd argue that instead of having `isPurchaseEnabled` variable, you should use `Pausable` contract from open zeppelin and make use of `whenNotPaused` modifiers. Notice that `Pausable` is already `Owned` so you won't have to inherit both contract in `Crowdsale`.

**Comment by 3th3r3um** [comment]
Good idea, just made a pull request with this now.
