### ISSUE TITLE
Get initial presale parameters.

### ISSUE THREAD

**Issue by 3th3r3um** [Onessus/void-token#3]
The latest updated ICO plan I had in my inbox was from 11/02/2017. I've copied the contents below. Dante, if you want to make any changes, drop a comment below. Right now, we're only developing the migrations/deployment logic for the first round (Stage 1), so don't worry so much about the later stages. Those can be adjusted as we approach each subsequent stage.

Stage 0:

Private Presale (Ongoing)

Stage 1:

Start Date: TBA
Incentive: 2,000 Odyssey/$1
Countdown preceding sale: 20 days
Length of sale: 2 weeks ( With capability to extend )
Hard cap: $100,000
Goal: $60,000

Stage 2:

Start Date: TBA
Incentive: 1,700 Odyssey/$1
Countdown preceding sale: 20 days
Length of sale: 2 weeks ( With capability to extend )
Hard cap: $400,000
Goal: $300,000

Stage 3:

Start Date: TBA
Incentive: Starting at 1,200 Odyssey/$1 and ending at 700 Odyssey/$1 (Every 2 weeks or every $5 million invested the price should
progressively & proportionately decrease until the bottom 700 Odyssey/$1 is reached.)
Countdown preceding sale: 40 days
Length of sale: 5 Months ( With capability to extend )
Hard cap: $50,000,000
Goal: $50,000,000

**Comment by 3th3r3um** [comment]
Also, one thing to keep in mind. The token rate can be changed to account for fluctuations in the ETH/USD price. But the hardcap by nature cannot be changed. Once `cap` is set for that round, the maximum number of tokens sold for that round is fixed regardless of if the rate changes or not. Personally, I do not think that this is an issue, but I think it's worth bringing to your attention.

**Comment by DanteScott** [comment]
Stage 1:

Start Date: TBA
Incentive: 2,000,000 Void/ETH
Countdown preceding sale: 20 days
Length of sale: 2 weeks ( With capability to extend )
Hard cap: 100 ETH
Soft Cap: 50 ETH

Stage 2:

Start Date: TBA
Incentive: 1,700,000 Void/ETH
Countdown preceding sale: 20 days
Length of sale: 2 weeks ( With capability to extend )
Hard cap: 400 ETH
Soft cap: 100 ETH

Stage 3:

Start Date: TBA
Incentive: Starting at 1,200,000 Void/ETH and ending at 700,000 Void/ETH (Every 2 weeks or every $5 million invested the price should
progressively & proportionately decrease until the bottom 700,000 Void/ETH is reached.)
Countdown preceding sale: 40 days
Length of sale: 5 Months ( With capability to extend )
Hard cap: 50,000 ETH
Soft cap: 1,000 ETH
