### ISSUE TITLE
Write tests for MultipleOwners.sol.

### ISSUE THREAD

**Issue by 3th3r3um** [Onessus/void-token#31]
I'll add a new test file for MultipleOwners.sol, along with some empty tests that should be filled out. Once you get those written, reference the issue in a pull request. Then I can review the pull request and merge it in.

**Comment by amanuelz91** [comment]
Cool, i'm currently writing these.

**Comment by 3th3r3um** [comment]
I merged the pull request before I had a chance to go through and see what was broken. I left some comments on the request. In the future, if tests are broken I'd prefer that you get them working on your local machine before pulling. Reviews should primarily be for finding bugs or things that the dev missed. It doesn't make sense to check in broken or commented code.

**Comment by amanuelz91** [comment]
Thanks for the feedback it was very helpful.
